-- Create the user_favorites table to store team preferences
create table if not exists public.user_favorites (
    id bigint generated by default as identity primary key,
    user_id uuid references auth.users not null,
    team_name text not null,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    unique(user_id, team_name)
);

-- Enable Row Level Security (RLS)
alter table public.user_favorites enable row level security;

-- Create policies

-- 1. Allow users to view their own favorites
create policy "Users can view their own favorites"
on public.user_favorites for select
using ( auth.uid() = user_id );

-- 2. Allow users to insert their own favorites
create policy "Users can insert their own favorites"
on public.user_favorites for insert
with check ( auth.uid() = user_id );

-- 3. Allow users to delete their own favorites
create policy "Users can delete their own favorites"
on public.user_favorites for delete
using ( auth.uid() = user_id );

-- 4. Allow users to update their own favorites (though we mostly just insert/delete)
create policy "Users can update their own favorites"
on public.user_favorites for update
using ( auth.uid() = user_id );
